# Generated by Django 5.2.7 on 2026-07-15 09:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlgorithmDefinition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=64, unique=True)),
                ("name", models.CharField(max_length=128)),
                ("category", models.CharField(blank=True, default="", max_length=64)),
                ("description", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "governance_algorithm_definition",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="StoredArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("security_audit", "Security audit events"),
                            ("system_metric", "Operational system metrics"),
                            ("raw_video", "Raw uploaded video"),
                            ("evidence_media", "Evidence snapshots/clips"),
                            ("detection_metadata", "Raw detection metadata"),
                            ("track_metadata", "Track-level metadata"),
                            ("traffic_measurement", "Traffic measurements"),
                            ("aggregated_analytics", "Aggregated analytics"),
                            ("model_artifact", "AI model artifacts"),
                            ("simulation_artifact", "Simulation artifacts"),
                            ("export", "Generated exports"),
                        ],
                        max_length=32,
                    ),
                ),
                ("path", models.CharField(max_length=512)),
                (
                    "checksum_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "governance_stored_artifact",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIModel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("family", models.CharField(max_length=128)),
                (
                    "task",
                    models.CharField(
                        choices=[
                            ("detection", "Object detection"),
                            ("tracking", "Object tracking"),
                            ("prediction", "Traffic prediction"),
                            ("anomaly", "Anomaly detection"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                ("provider", models.CharField(blank=True, default="", max_length=128)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "governance_ai_model",
                "ordering": ["family", "task"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("family", "task", "provider"),
                        name="uq_aimodel_family_task_provider",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AIModelVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.CharField(max_length=64)),
                (
                    "provenance",
                    models.CharField(
                        choices=[
                            ("pretrained", "Third-party pretrained"),
                            ("finetuned", "Fine-tuned"),
                            ("platform_trained", "Trained by this platform"),
                            ("imported", "Imported custom model"),
                            ("traditional_ml", "Traditional ML"),
                        ],
                        max_length=32,
                    ),
                ),
                ("license", models.CharField(blank=True, default="", max_length=128)),
                (
                    "source_url",
                    models.CharField(blank=True, default="", max_length=512),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("input_spec", models.JSONField(blank=True, default=dict)),
                (
                    "output_schema_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("class_map", models.JSONField(blank=True, default=dict)),
                ("benchmark_summary", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=False)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="governance.aimodel",
                    ),
                ),
            ],
            options={
                "db_table": "governance_ai_model_version",
                "ordering": ["model", "version"],
            },
        ),
        migrations.CreateModel(
            name="AlgorithmVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version", models.CharField(max_length=64)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("config_hash", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="governance.algorithmdefinition",
                    ),
                ),
            ],
            options={
                "db_table": "governance_algorithm_version",
                "ordering": ["definition", "version"],
            },
        ),
        migrations.CreateModel(
            name="ModelArtifact",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("weights", "Weights"),
                            ("config", "Config"),
                            ("labels", "Labels"),
                        ],
                        max_length=16,
                    ),
                ),
                ("path", models.CharField(max_length=512)),
                (
                    "checksum_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("size_bytes", models.BigIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifacts",
                        to="governance.aimodelversion",
                    ),
                ),
            ],
            options={
                "db_table": "governance_model_artifact",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ModelEvaluation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "dataset_ref",
                    models.CharField(blank=True, default="", max_length=256),
                ),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("provenance_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluations",
                        to="governance.aimodelversion",
                    ),
                ),
            ],
            options={
                "db_table": "governance_model_evaluation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="aimodelversion",
            constraint=models.UniqueConstraint(
                fields=("model", "version"), name="uq_aimodelversion_model_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="algorithmversion",
            constraint=models.UniqueConstraint(
                fields=("definition", "version"), name="uq_algoversion_def_version"
            ),
        ),
    ]
