# Generated by Django 5.2.7 on 2026-07-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storedartifact",
            name="state",
            field=models.CharField(
                choices=[
                    ("present", "Present"),
                    ("orphaned", "Orphaned"),
                    ("deleted", "Deleted"),
                ],
                default="present",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="storedartifact",
            name="category",
            field=models.CharField(
                choices=[
                    ("security_audit", "Security audit events"),
                    ("system_metric", "Operational system metrics"),
                    ("raw_video", "Raw uploaded video"),
                    ("evidence_media", "Evidence snapshots/clips"),
                    ("detection_metadata", "Raw detection metadata"),
                    ("track_metadata", "Track-level metadata"),
                    ("traffic_measurement", "Traffic measurements"),
                    ("aggregated_analytics", "Aggregated analytics"),
                    ("model_artifact", "AI model artifacts"),
                    ("simulation_artifact", "Simulation artifacts"),
                    ("export", "Generated exports"),
                    ("traffic_config", "Traffic network configuration"),
                    ("video_thumbnail", "Video thumbnail image"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="storedartifact",
            index=models.Index(
                fields=["category", "state"], name="governance__categor_24f203_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="storedartifact",
            index=models.Index(
                fields=["checksum_sha256"], name="governance__checksu_067890_idx"
            ),
        ),
    ]
