# Generated by Django 5.2.7 on 2026-07-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "governance",
            "0002_storedartifact_state_alter_storedartifact_category_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="aimodelversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("training", "Training"),
                    ("evaluated", "Evaluated"),
                    ("candidate", "Candidate"),
                    ("approved", "Approved"),
                    ("active", "Active"),
                    ("retired", "Retired"),
                    ("test_only", "Test-only (never production)"),
                ],
                default="draft",
                max_length=16,
            ),
        ),
    ]
