# Generated by Django 5.2.7 on 2026-07-16 09:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0003_aimodelversion_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedartifact",
            name="category",
            field=models.CharField(
                choices=[
                    ("security_audit", "Security audit events"),
                    ("system_metric", "Operational system metrics"),
                    ("raw_video", "Raw uploaded video"),
                    ("evidence_media", "Evidence snapshots/clips"),
                    ("detection_metadata", "Raw detection metadata"),
                    ("track_metadata", "Track-level metadata"),
                    ("traffic_measurement", "Traffic measurements"),
                    ("aggregated_analytics", "Aggregated analytics"),
                    ("model_artifact", "AI model artifacts"),
                    ("simulation_artifact", "Simulation artifacts"),
                    ("export", "Generated exports"),
                    ("traffic_config", "Traffic network configuration"),
                    ("video_thumbnail", "Video thumbnail image"),
                    ("training_data", "Training dataset media"),
                    ("dataset_manifest", "Immutable dataset/split manifest"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="TrainingRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("architecture", models.CharField(max_length=64)),
                ("code_identity", models.CharField(max_length=64)),
                (
                    "code_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "config_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("recipe", models.JSONField(blank=True, default=dict)),
                ("dataset_version_ids", models.JSONField(blank=True, default=list)),
                (
                    "split_manifest_sha256",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "taxonomy_version",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "class_mapping_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "preprocess_contract",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("seed", models.BigIntegerField(blank=True, null=True)),
                ("framework_versions", models.JSONField(blank=True, default=dict)),
                ("hardware", models.CharField(blank=True, default="", max_length=256)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("interrupted", "Interrupted"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("metrics", models.JSONField(blank=True, default=dict)),
                (
                    "best_checkpoint_ref",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "exported_artifact_ref",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                ("failure_info", models.TextField(blank=True, default="")),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="training_runs",
                        to="governance.aimodelversion",
                    ),
                ),
            ],
            options={
                "db_table": "governance_training_run",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["architecture", "status"],
                        name="governance__archite_76716d_idx",
                    )
                ],
            },
        ),
    ]
