# Generated by Django 5.2.7 on 2026-07-15 09:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RetentionPolicy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("security_audit", "Security audit events"),
                            ("system_metric", "Operational system metrics"),
                            ("raw_video", "Raw uploaded video"),
                            ("evidence_media", "Evidence snapshots/clips"),
                            ("detection_metadata", "Raw detection metadata"),
                            ("track_metadata", "Track-level metadata"),
                            ("traffic_measurement", "Traffic measurements"),
                            ("aggregated_analytics", "Aggregated analytics"),
                            ("model_artifact", "AI model artifacts"),
                            ("simulation_artifact", "Simulation artifacts"),
                            ("export", "Generated exports"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("retention_days", models.PositiveIntegerField()),
                ("enabled", models.BooleanField(default=False)),
                (
                    "deletion_strategy",
                    models.CharField(
                        choices=[
                            ("hard", "Hard delete"),
                            ("archive", "Archive then delete"),
                        ],
                        default="hard",
                        max_length=16,
                    ),
                ),
                ("batch_size", models.PositiveIntegerField(default=1000)),
                ("max_deletes_per_run", models.PositiveIntegerField(default=100000)),
                ("dry_run_default", models.BooleanField(default=True)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "retention_policy",
                "ordering": ["category"],
            },
        ),
        migrations.CreateModel(
            name="RetentionRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("dry_run", models.BooleanField(default=True)),
                ("scanned", models.BigIntegerField(default=0)),
                ("deleted", models.BigIntegerField(default=0)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("partial", "Partial"),
                            ("skipped", "Skipped"),
                        ],
                        default="success",
                        max_length=16,
                    ),
                ),
                ("error", models.TextField(blank=True, default="")),
                ("request_id", models.CharField(blank=True, default="", max_length=64)),
                ("source", models.CharField(default="celery", max_length=16)),
                (
                    "policy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="retention.retentionpolicy",
                    ),
                ),
            ],
            options={
                "db_table": "retention_run",
                "ordering": ["-started_at"],
                "indexes": [
                    models.Index(
                        fields=["policy", "started_at"],
                        name="retention_r_policy__b7f7c0_idx",
                    )
                ],
            },
        ),
    ]
