# Generated by Django 5.2.7 on 2026-07-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("retention", "0003_alter_retentionpolicy_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="retentionpolicy",
            name="category",
            field=models.CharField(
                choices=[
                    ("security_audit", "Security audit events"),
                    ("system_metric", "Operational system metrics"),
                    ("raw_video", "Raw uploaded video"),
                    ("evidence_media", "Evidence snapshots/clips"),
                    ("detection_metadata", "Raw detection metadata"),
                    ("track_metadata", "Track-level metadata"),
                    ("traffic_measurement", "Traffic measurements"),
                    ("aggregated_analytics", "Aggregated analytics"),
                    ("model_artifact", "AI model artifacts"),
                    ("simulation_artifact", "Simulation artifacts"),
                    ("export", "Generated exports"),
                    ("traffic_config", "Traffic network configuration"),
                    ("video_thumbnail", "Video thumbnail image"),
                    ("training_data", "Training dataset media"),
                    ("dataset_manifest", "Immutable dataset/split manifest"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
    ]
