# Generated by Django 5.2.7 on 2026-07-15 09:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("login_success", "Login success"),
                            ("login_failure", "Login failure"),
                            ("logout", "Logout"),
                            ("user_created", "User created"),
                            ("user_updated", "User updated"),
                            ("user_activated", "User activated"),
                            ("user_deactivated", "User deactivated"),
                            ("role_changed", "Role changed"),
                            ("user_deleted", "User deleted"),
                            ("retention_run", "Retention run executed"),
                            ("model_activated", "Model version activated"),
                            ("model_deactivated", "Model version deactivated"),
                            ("algorithm_activated", "Algorithm version activated"),
                        ],
                        db_index=True,
                        max_length=48,
                    ),
                ),
                ("action", models.CharField(max_length=128)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failure", "Failure"),
                            ("denied", "Denied"),
                        ],
                        default="success",
                        max_length=16,
                    ),
                ),
                ("actor_id", models.UUIDField(blank=True, db_index=True, null=True)),
                (
                    "actor_email",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                ("actor_role", models.CharField(blank=True, default="", max_length=32)),
                (
                    "target_type",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=64
                    ),
                ),
                ("target_id", models.CharField(blank=True, default="", max_length=64)),
                ("request_id", models.CharField(blank=True, default="", max_length=64)),
                ("source", models.CharField(default="django", max_length=16)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "audit_event",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="audit_event_event_t_08fe33_idx",
                    ),
                    models.Index(
                        fields=["actor_id", "created_at"],
                        name="audit_event_actor_i_032040_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="audit_event_target__92b051_idx",
                    ),
                ],
            },
        ),
    ]
