# Generated by Django 5.2.7 on 2026-07-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_alter_auditevent_event_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("login_success", "Login success"),
                    ("login_failure", "Login failure"),
                    ("logout", "Logout"),
                    ("user_created", "User created"),
                    ("user_updated", "User updated"),
                    ("user_activated", "User activated"),
                    ("user_deactivated", "User deactivated"),
                    ("role_changed", "Role changed"),
                    ("user_deleted", "User deleted"),
                    ("retention_run", "Retention run executed"),
                    ("model_activated", "Model version activated"),
                    ("model_deactivated", "Model version deactivated"),
                    ("algorithm_activated", "Algorithm version activated"),
                    ("model_approved", "Model version approved"),
                    ("network_config_created", "Network config created"),
                    ("network_config_updated", "Network config updated"),
                    ("network_config_archived", "Network config archived"),
                    ("network_config_deleted", "Network config deleted"),
                    ("video_uploaded", "Video uploaded"),
                    ("video_validation_failed", "Video validation failed"),
                    ("video_archived", "Video archived"),
                    ("video_deleted", "Video deleted"),
                    ("processing_requested", "Processing requested"),
                    ("processing_queued", "Processing queued"),
                    ("processing_started", "Processing started"),
                    ("processing_paused", "Processing paused"),
                    ("processing_resumed", "Processing resumed"),
                    (
                        "processing_cancel_requested",
                        "Processing cancellation requested",
                    ),
                    ("processing_cancelled", "Processing cancelled"),
                    ("processing_stopped", "Processing stopped"),
                    ("processing_completed", "Processing completed"),
                    ("processing_failed", "Processing failed"),
                    ("processing_retry_requested", "Processing retry requested"),
                ],
                db_index=True,
                max_length=48,
            ),
        ),
    ]
