# Generated by Django 5.2.7 on 2026-07-15 09:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SystemMetric",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=64)),
                ("runtime", models.CharField(default="django", max_length=16)),
                ("component", models.CharField(blank=True, default="", max_length=64)),
                ("value", models.FloatField()),
                ("unit", models.CharField(default="count", max_length=16)),
                ("labels", models.JSONField(blank=True, default=dict)),
                ("host", models.CharField(blank=True, default="", max_length=128)),
                ("process", models.CharField(blank=True, default="", max_length=64)),
                ("bucket_start", models.DateTimeField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "db_table": "observability_system_metric",
                "ordering": ["-bucket_start"],
                "indexes": [
                    models.Index(
                        fields=["name", "bucket_start"],
                        name="observabili_name_908e05_idx",
                    )
                ],
            },
        ),
    ]
