# Generated by Django 5.2.7 on 2026-07-15 16:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ingestion", "0002_seed_video_retention"),
        ("network", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessingConfigSnapshot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("snapshot_schema_version", models.PositiveIntegerField(default=1)),
                ("payload", models.JSONField()),
                (
                    "snapshot_hash",
                    models.CharField(db_index=True, max_length=64, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "processing_config_snapshot",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProcessingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processing_params", models.JSONField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("queued", "Queued"),
                            ("initializing", "Initializing"),
                            ("running", "Running"),
                            ("pausing", "Pausing"),
                            ("paused", "Paused"),
                            ("resuming", "Resuming"),
                            ("completing", "Completing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("stopped", "Stopped"),
                        ],
                        db_index=True,
                        default="created",
                        max_length=16,
                    ),
                ),
                (
                    "requested_action",
                    models.CharField(
                        choices=[
                            ("none", "None"),
                            ("pause", "Pause"),
                            ("resume", "Resume"),
                            ("stop", "Stop"),
                            ("cancel", "Cancel"),
                        ],
                        default="none",
                        max_length=8,
                    ),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("runtime_id", models.CharField(blank=True, default="", max_length=64)),
                (
                    "runtime_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("device", models.CharField(blank=True, default="", max_length=32)),
                ("error_code", models.CharField(blank=True, default="", max_length=48)),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "frames_total_estimate",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("frames_decoded", models.BigIntegerField(default=0)),
                ("frames_processed", models.BigIntegerField(default=0)),
                ("current_frame_index", models.BigIntegerField(blank=True, null=True)),
                ("current_pts_seconds", models.FloatField(blank=True, null=True)),
                ("progress_percent", models.FloatField(blank=True, null=True)),
                ("decode_fps", models.FloatField(blank=True, null=True)),
                ("processing_fps", models.FloatField(blank=True, null=True)),
                ("last_heartbeat_at", models.DateTimeField(blank=True, null=True)),
                ("queued_at", models.DateTimeField(blank=True, null=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("paused_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("stopped_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_requested_at", models.DateTimeField(blank=True, null=True)),
                (
                    "camera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processing_sessions",
                        to="network.camera",
                    ),
                ),
                (
                    "config_snapshot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="sessions",
                        to="processing.processingconfigsnapshot",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "retry_of",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="retries",
                        to="processing.processingsession",
                    ),
                ),
                (
                    "video_asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="processing_sessions",
                        to="ingestion.videoasset",
                    ),
                ),
            ],
            options={
                "db_table": "processing_session",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["state", "last_heartbeat_at"],
                        name="processing__state_2543d0_idx",
                    ),
                    models.Index(
                        fields=["video_asset", "state"],
                        name="processing__video_a_4df60b_idx",
                    ),
                    models.Index(
                        fields=["camera", "created_at"],
                        name="processing__camera__fc7cb3_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "state__in",
                                [
                                    "created",
                                    "queued",
                                    "initializing",
                                    "running",
                                    "pausing",
                                    "paused",
                                    "resuming",
                                    "completing",
                                    "completed",
                                    "failed",
                                    "cancelled",
                                    "stopped",
                                ],
                            )
                        ),
                        name="ck_processing_session_state_enum",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "state__in",
                                [
                                    "completing",
                                    "created",
                                    "initializing",
                                    "paused",
                                    "pausing",
                                    "queued",
                                    "resuming",
                                    "running",
                                ],
                            )
                        ),
                        fields=("video_asset",),
                        name="uq_processing_active_per_video",
                    ),
                ],
            },
        ),
    ]
