# Generated by Django 5.2.7 on 2026-07-15 17:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("governance", "0003_aimodelversion_status"),
        ("ingestion", "0002_seed_video_retention"),
        ("processing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrameDetectionBatch",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("provider_name", models.CharField(max_length=64)),
                (
                    "provider_version",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("is_test_provider", models.BooleanField(default=False)),
                ("taxonomy_version", models.CharField(max_length=16)),
                ("source_frame_index", models.BigIntegerField()),
                ("pts_seconds", models.FloatField(blank=True, null=True)),
                ("detection_count", models.PositiveIntegerField(default=0)),
                ("detections", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "model_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="governance.aimodelversion",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detection_batches",
                        to="processing.processingsession",
                    ),
                ),
                (
                    "video",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="ingestion.videoasset",
                    ),
                ),
            ],
            options={
                "db_table": "processing_frame_detection_batch",
                "ordering": ["session", "source_frame_index"],
                "indexes": [
                    models.Index(
                        fields=["session", "source_frame_index"],
                        name="processing__session_cad5ab_idx",
                    ),
                    models.Index(
                        fields=["video", "source_frame_index"],
                        name="processing__video_i_1cea5f_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("session", "source_frame_index"),
                        name="uq_detection_batch_session_frame",
                    )
                ],
            },
        ),
    ]
