# Generated by Django 5.2.7 on 2026-07-15 10:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("code", models.CharField(max_length=32, unique=True)),
                (
                    "country_code",
                    models.CharField(blank=True, default="", max_length=2),
                ),
                (
                    "timezone",
                    models.CharField(blank=True, default="UTC", max_length=64),
                ),
                (
                    "center_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "center_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("boundary", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "network_city",
                "ordering": ["code"],
                "indexes": [
                    models.Index(
                        fields=["is_active"], name="network_cit_is_acti_8db412_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Intersection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("code", models.CharField(max_length=32)),
                (
                    "location_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "location_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "intersection_type",
                    models.CharField(
                        choices=[
                            ("signalized", "Signalized"),
                            ("unsignalized", "Unsignalized"),
                            ("roundabout", "Roundabout"),
                            ("junction", "Junction"),
                            ("other", "Other"),
                        ],
                        default="junction",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="intersections",
                        to="network.city",
                    ),
                ),
            ],
            options={
                "db_table": "network_intersection",
                "ordering": ["city", "code"],
            },
        ),
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "config_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("name", models.CharField(max_length=128)),
                ("code", models.CharField(max_length=32)),
                (
                    "location_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "location_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "bearing_deg",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "camera_type",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed"),
                            ("ptz", "PTZ"),
                            ("dome", "Dome"),
                            ("other", "Other"),
                        ],
                        default="fixed",
                        max_length=16,
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded video (future)"),
                            ("rtsp", "RTSP (future)"),
                            ("simulated", "Simulated (future)"),
                            ("unconfigured", "Unconfigured"),
                        ],
                        default="unconfigured",
                        max_length=16,
                    ),
                ),
                ("install_metadata", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cameras",
                        to="network.city",
                    ),
                ),
                (
                    "intersection",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cameras",
                        to="network.intersection",
                    ),
                ),
            ],
            options={
                "db_table": "network_camera",
                "ordering": ["city", "code"],
            },
        ),
        migrations.CreateModel(
            name="Approach",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("N", "North"),
                            ("NE", "Northeast"),
                            ("E", "East"),
                            ("SE", "Southeast"),
                            ("S", "South"),
                            ("SW", "Southwest"),
                            ("W", "West"),
                            ("NW", "Northwest"),
                        ],
                        default="",
                        max_length=2,
                    ),
                ),
                (
                    "bearing_deg",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "approach_type",
                    models.CharField(
                        choices=[
                            ("incoming", "Incoming"),
                            ("outgoing", "Outgoing"),
                            ("bidirectional", "Bidirectional"),
                        ],
                        default="incoming",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "intersection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="approaches",
                        to="network.intersection",
                    ),
                ),
            ],
            options={
                "db_table": "network_approach",
                "ordering": ["intersection"],
            },
        ),
        migrations.CreateModel(
            name="Lane",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "config_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("lane_index", models.PositiveSmallIntegerField()),
                (
                    "direction",
                    models.CharField(
                        choices=[("forward", "Forward"), ("backward", "Backward")],
                        default="forward",
                        max_length=8,
                    ),
                ),
                (
                    "lane_type",
                    models.CharField(
                        choices=[
                            ("general", "General traffic"),
                            ("bus", "Bus"),
                            ("bicycle", "Bicycle"),
                            ("emergency", "Emergency"),
                            ("turn", "Turn"),
                            ("parking", "Parking"),
                            ("shoulder", "Shoulder"),
                        ],
                        default="general",
                        max_length=16,
                    ),
                ),
                ("geometry", models.JSONField(blank=True, null=True)),
                (
                    "width_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "speed_limit_override_kph",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "approach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="lanes",
                        to="network.approach",
                    ),
                ),
            ],
            options={
                "db_table": "network_lane",
                "ordering": ["road_segment", "lane_index"],
            },
        ),
        migrations.CreateModel(
            name="CameraLaneCoverage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "coverage_type",
                    models.CharField(
                        choices=[
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("partial", "Partial"),
                        ],
                        default="primary",
                        max_length=16,
                    ),
                ),
                ("priority", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverages",
                        to="network.camera",
                    ),
                ),
                (
                    "lane",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverages",
                        to="network.lane",
                    ),
                ),
            ],
            options={
                "db_table": "network_camera_lane_coverage",
                "ordering": ["camera", "priority"],
            },
        ),
        migrations.AddField(
            model_name="camera",
            name="lanes",
            field=models.ManyToManyField(
                related_name="cameras",
                through="network.CameraLaneCoverage",
                to="network.lane",
            ),
        ),
        migrations.CreateModel(
            name="RegionOfInterest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "config_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("name", models.CharField(max_length=128)),
                (
                    "roi_type",
                    models.CharField(
                        choices=[
                            ("detection", "Detection area"),
                            ("ignore", "Ignore area"),
                            ("incident", "Incident zone"),
                            ("lane_area", "Lane area"),
                        ],
                        default="detection",
                        max_length=16,
                    ),
                ),
                ("polygon", models.JSONField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rois",
                        to="network.camera",
                    ),
                ),
                (
                    "lane",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rois",
                        to="network.lane",
                    ),
                ),
            ],
            options={
                "db_table": "network_region_of_interest",
                "ordering": ["camera", "name"],
            },
        ),
        migrations.CreateModel(
            name="Road",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("code", models.CharField(max_length=32)),
                (
                    "road_type",
                    models.CharField(
                        choices=[
                            ("motorway", "Motorway"),
                            ("trunk", "Trunk"),
                            ("primary", "Primary"),
                            ("secondary", "Secondary"),
                            ("tertiary", "Tertiary"),
                            ("residential", "Residential"),
                            ("service", "Service"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=16,
                    ),
                ),
                (
                    "directionality",
                    models.CharField(
                        choices=[("one_way", "One-way"), ("two_way", "Two-way")],
                        default="two_way",
                        max_length=8,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="roads",
                        to="network.city",
                    ),
                ),
            ],
            options={
                "db_table": "network_road",
                "ordering": ["city", "code"],
            },
        ),
        migrations.CreateModel(
            name="RoadSegment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "start_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "start_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "end_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "end_lng",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("geometry", models.JSONField(blank=True, null=True)),
                (
                    "length_m",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "length_source",
                    models.CharField(
                        choices=[
                            ("manual", "Manually entered"),
                            ("derived", "Derived from geometry"),
                        ],
                        default="manual",
                        max_length=8,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("forward", "Forward"),
                            ("backward", "Backward"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=8,
                    ),
                ),
                ("speed_limit_kph", models.PositiveIntegerField(blank=True, null=True)),
                ("lane_count", models.PositiveIntegerField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "road",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="segments",
                        to="network.road",
                    ),
                ),
            ],
            options={
                "db_table": "network_road_segment",
                "ordering": ["road"],
            },
        ),
        migrations.AddField(
            model_name="lane",
            name="road_segment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="lanes",
                to="network.roadsegment",
            ),
        ),
        migrations.AddField(
            model_name="approach",
            name="road_segment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approaches",
                to="network.roadsegment",
            ),
        ),
        migrations.CreateModel(
            name="StopLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "config_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("name", models.CharField(max_length=128)),
                ("line", models.JSONField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "approach",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stop_lines",
                        to="network.approach",
                    ),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stop_lines",
                        to="network.camera",
                    ),
                ),
                (
                    "lane",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stop_lines",
                        to="network.lane",
                    ),
                ),
            ],
            options={
                "db_table": "network_stop_line",
                "ordering": ["camera", "name"],
            },
        ),
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128)),
                ("code", models.CharField(max_length=32)),
                ("boundary", models.JSONField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="zones",
                        to="network.city",
                    ),
                ),
            ],
            options={
                "db_table": "network_zone",
                "ordering": ["city", "code"],
            },
        ),
        migrations.AddField(
            model_name="roadsegment",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="segments",
                to="network.zone",
            ),
        ),
        migrations.AddField(
            model_name="intersection",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intersections",
                to="network.zone",
            ),
        ),
        migrations.AddField(
            model_name="camera",
            name="zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cameras",
                to="network.zone",
            ),
        ),
        migrations.CreateModel(
            name="CountingLine",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("revision", models.PositiveIntegerField(default=1)),
                (
                    "config_hash",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("name", models.CharField(max_length=128)),
                ("start", models.JSONField()),
                ("end", models.JSONField()),
                (
                    "counting_direction",
                    models.CharField(
                        choices=[
                            ("a_to_b", "A→B"),
                            ("b_to_a", "B→A"),
                            ("both", "Both"),
                        ],
                        default="both",
                        max_length=8,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="counting_lines",
                        to="network.camera",
                    ),
                ),
                (
                    "lane",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="counting_lines",
                        to="network.lane",
                    ),
                ),
            ],
            options={
                "db_table": "network_counting_line",
                "ordering": ["camera", "name"],
                "indexes": [
                    models.Index(
                        fields=["camera", "is_active"],
                        name="network_cou_camera__a85c16_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("camera", "name"), name="uq_counting_line_camera_name"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="cameralanecoverage",
            index=models.Index(
                fields=["camera"], name="network_cam_camera__cd65e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="cameralanecoverage",
            index=models.Index(fields=["lane"], name="network_cam_lane_id_1ec731_idx"),
        ),
        migrations.AddConstraint(
            model_name="cameralanecoverage",
            constraint=models.UniqueConstraint(
                fields=("camera", "lane"), name="uq_coverage_camera_lane"
            ),
        ),
        migrations.AddIndex(
            model_name="regionofinterest",
            index=models.Index(
                fields=["camera", "is_active"], name="network_reg_camera__67d775_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="regionofinterest",
            constraint=models.UniqueConstraint(
                fields=("camera", "name"), name="uq_roi_camera_name"
            ),
        ),
        migrations.AddIndex(
            model_name="road",
            index=models.Index(
                fields=["city", "is_active"], name="network_roa_city_id_7e3b73_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="road",
            constraint=models.UniqueConstraint(
                fields=("city", "code"), name="uq_road_city_code"
            ),
        ),
        migrations.AddIndex(
            model_name="lane",
            index=models.Index(
                fields=["road_segment", "is_active"],
                name="network_lan_road_se_198c1e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="lane",
            index=models.Index(
                fields=["approach"], name="network_lan_approac_45f1b1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="lane",
            constraint=models.UniqueConstraint(
                fields=("road_segment", "lane_index", "direction"),
                name="uq_lane_segment_index_direction",
            ),
        ),
        migrations.AddIndex(
            model_name="approach",
            index=models.Index(
                fields=["intersection"], name="network_app_interse_7d1a9e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="approach",
            index=models.Index(
                fields=["road_segment"], name="network_app_road_se_f88127_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stopline",
            index=models.Index(
                fields=["camera", "is_active"], name="network_sto_camera__57855a_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stopline",
            constraint=models.UniqueConstraint(
                fields=("camera", "name"), name="uq_stop_line_camera_name"
            ),
        ),
        migrations.AddIndex(
            model_name="zone",
            index=models.Index(
                fields=["city", "is_active"], name="network_zon_city_id_ee3053_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="zone",
            constraint=models.UniqueConstraint(
                fields=("city", "code"), name="uq_zone_city_code"
            ),
        ),
        migrations.AddIndex(
            model_name="roadsegment",
            index=models.Index(
                fields=["road", "is_active"], name="network_roa_road_id_06fcb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roadsegment",
            index=models.Index(fields=["zone"], name="network_roa_zone_id_63c75d_idx"),
        ),
        migrations.AddIndex(
            model_name="intersection",
            index=models.Index(
                fields=["city", "is_active"], name="network_int_city_id_593f05_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="intersection",
            index=models.Index(fields=["zone"], name="network_int_zone_id_673761_idx"),
        ),
        migrations.AddConstraint(
            model_name="intersection",
            constraint=models.UniqueConstraint(
                fields=("city", "code"), name="uq_intersection_city_code"
            ),
        ),
        migrations.AddIndex(
            model_name="camera",
            index=models.Index(
                fields=["city", "is_active"], name="network_cam_city_id_72f385_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="camera",
            index=models.Index(
                fields=["intersection"], name="network_cam_interse_96da44_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="camera",
            index=models.Index(fields=["zone"], name="network_cam_zone_id_d0be62_idx"),
        ),
        migrations.AddConstraint(
            model_name="camera",
            constraint=models.UniqueConstraint(
                fields=("city", "code"), name="uq_camera_city_code"
            ),
        ),
    ]
