# Generated by Django 5.2.7 on 2026-07-15 10:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "governance",
            "0002_storedartifact_state_alter_storedartifact_category_and_more",
        ),
        ("network", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_filename",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("storage_key", models.CharField(max_length=512)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("uploaded_file", "Uploaded file"),
                            ("rtsp", "RTSP (reserved)"),
                            ("webcam", "Webcam (reserved)"),
                            ("nvr", "NVR (reserved)"),
                            ("disk_path", "Disk path (reserved)"),
                        ],
                        default="uploaded_file",
                        max_length=16,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("size_bytes", models.BigIntegerField()),
                ("checksum_sha256", models.CharField(max_length=64)),
                (
                    "mime_detected",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                (
                    "container_format",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                ("codec", models.CharField(blank=True, default="", max_length=32)),
                ("duration_s", models.FloatField(blank=True, null=True)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("fps", models.FloatField(blank=True, null=True)),
                ("frame_count", models.BigIntegerField(blank=True, null=True)),
                (
                    "validation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("valid", "Valid"),
                            ("invalid", "Invalid"),
                            ("quarantined", "Quarantined"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("error_code", models.CharField(blank=True, default="", max_length=48)),
                (
                    "error_message",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("has_thumbnail", models.BooleanField(default=False)),
                ("recording_started_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recording_time_source",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "privacy_status",
                    models.CharField(
                        choices=[
                            ("raw_unprocessed", "Raw / unprocessed"),
                            ("anonymized", "Anonymized (reserved)"),
                        ],
                        default="raw_unprocessed",
                        max_length=16,
                    ),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_assets",
                        to="network.camera",
                    ),
                ),
                (
                    "stored_artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="video_assets",
                        to="governance.storedartifact",
                    ),
                ),
                (
                    "thumbnail_artifact",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="thumbnail_of",
                        to="governance.storedartifact",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "ingestion_video_asset",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["checksum_sha256"],
                        name="ingestion_v_checksu_038131_idx",
                    ),
                    models.Index(
                        fields=["camera", "is_active"],
                        name="ingestion_v_camera__45fbd8_idx",
                    ),
                    models.Index(
                        fields=["validation_status", "is_active"],
                        name="ingestion_v_validat_969a79_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("checksum_sha256",),
                        name="uq_video_active_checksum",
                    )
                ],
            },
        ),
    ]
